[2024-11-30T08:18:43.603+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T08:18:43.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt-viz-dag.dbt_snapshot manual__2024-11-30T08:18:03.097168+00:00 [queued]>
[2024-11-30T08:18:43.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt-viz-dag.dbt_snapshot manual__2024-11-30T08:18:03.097168+00:00 [queued]>
[2024-11-30T08:18:43.672+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-30T08:18:43.823+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-30 08:18:03.097168+00:00
[2024-11-30T08:18:43.874+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=810) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T08:18:43.875+0000] {standard_task_runner.py:63} INFO - Started process 811 to run task
[2024-11-30T08:18:43.869+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt-viz-dag', 'dbt_snapshot', 'manual__2024-11-30T08:18:03.097168+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/dbt-viz-dag.py', '--cfg-path', '/tmp/tmpq0rnrtyw']
[2024-11-30T08:18:43.895+0000] {standard_task_runner.py:91} INFO - Job 405: Subtask dbt_snapshot
[2024-11-30T08:18:44.952+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt-viz-dag.dbt_snapshot manual__2024-11-30T08:18:03.097168+00:00 [running]> on host e060654747dc
[2024-11-30T08:18:45.297+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt-viz-dag' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T08:18:03.097168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T08:18:03.097168+00:00'
[2024-11-30T08:18:45.299+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T08:18:45.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-30T08:18:45.327+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt_viz --project-dir /opt/***/dbt_viz']
[2024-11-30T08:18:45.349+0000] {subprocess.py:86} INFO - Output:
[2024-11-30T08:18:49.149+0000] {subprocess.py:93} INFO - [0m08:18:49  Running with dbt=1.8.7
[2024-11-30T08:18:50.644+0000] {subprocess.py:93} INFO - [0m08:18:50  Registered adapter: snowflake=1.8.4
[2024-11-30T08:18:51.414+0000] {subprocess.py:93} INFO - [0m08:18:51  Found 3 models, 1 test, 3 sources, 459 macros
[2024-11-30T08:18:51.419+0000] {subprocess.py:93} INFO - [0m08:18:51
[2024-11-30T08:18:51.421+0000] {subprocess.py:93} INFO - [0m08:18:51  Nothing to do. Try checking your model configs and model specification args
[2024-11-30T08:18:52.600+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-30T08:18:52.602+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T08:18:52.643+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt-viz-dag, task_id=dbt_snapshot, run_id=manual__2024-11-30T08:18:03.097168+00:00, execution_date=20241130T081803, start_date=20241130T081843, end_date=20241130T081852
[2024-11-30T08:18:52.674+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-30T08:18:52.701+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T08:18:52.706+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
