[2024-11-12T02:33:54.614+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T02:33:54.773+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T02:33:51.605811+00:00 [queued]>
[2024-11-12T02:33:54.788+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T02:33:51.605811+00:00 [queued]>
[2024-11-12T02:33:54.789+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T02:33:54.835+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 02:33:51.605811+00:00
[2024-11-12T02:33:54.854+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-12T02:33:51.605811+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpdyuo0izm']
[2024-11-12T02:33:54.908+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask dbt_run
[2024-11-12T02:33:54.925+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=411) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T02:33:54.927+0000] {standard_task_runner.py:63} INFO - Started process 412 to run task
[2024-11-12T02:33:55.295+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T02:33:51.605811+00:00 [running]> on host 1381f02c4e31
[2024-11-12T02:33:56.022+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T02:33:51.605811+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T02:33:51.605811+00:00'
[2024-11-12T02:33:56.025+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T02:33:56.291+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T02:33:56.299+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T02:33:56.324+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T02:34:02.560+0000] {subprocess.py:93} INFO - [0m02:34:02  Running with dbt=1.8.7
[2024-11-12T02:34:02.624+0000] {subprocess.py:93} INFO - [0m02:34:02  Encountered an error:
[2024-11-12T02:34:02.625+0000] {subprocess.py:93} INFO - Runtime Error
[2024-11-12T02:34:02.625+0000] {subprocess.py:93} INFO -   Could not find profile named 'lab2'
[2024-11-12T02:34:04.406+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T02:34:04.477+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T02:34:04.500+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T02:34:04.520+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-12T02:33:51.605811+00:00, execution_date=20241112T023351, start_date=20241112T023354, end_date=20241112T023404
[2024-11-12T02:34:04.547+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 122 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 412)
[2024-11-12T02:34:04.594+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T02:34:04.625+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T02:34:04.630+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
