[2024-11-29T17:56:33.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-29T17:56:33.652+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Electricity_predict.predict manual__2024-11-29T17:56:26.610134+00:00 [queued]>
[2024-11-29T17:56:33.665+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Electricity_predict.predict manual__2024-11-29T17:56:26.610134+00:00 [queued]>
[2024-11-29T17:56:33.666+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-29T17:56:33.686+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): predict> on 2024-11-29 17:56:26.610134+00:00
[2024-11-29T17:56:33.701+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Electricity_predict', 'predict', 'manual__2024-11-29T17:56:26.610134+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/energy_usage_prediction.py', '--cfg-path', '/tmp/tmpfsidybx8']
[2024-11-29T17:56:33.704+0000] {standard_task_runner.py:91} INFO - Job 269: Subtask predict
[2024-11-29T17:56:33.706+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10401) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T17:56:33.708+0000] {standard_task_runner.py:63} INFO - Started process 10414 to run task
[2024-11-29T17:56:33.777+0000] {task_command.py:426} INFO - Running <TaskInstance: Electricity_predict.predict manual__2024-11-29T17:56:26.610134+00:00 [running]> on host fd43cd87157f
[2024-11-29T17:56:33.906+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Electricity_predict' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T17:56:26.610134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-29T17:56:26.610134+00:00'
[2024-11-29T17:56:33.908+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-29T17:56:55.019+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-29T17:56:55.020+0000] {energy_usage_prediction.py:111} INFO - prediction created
[2024-11-29T17:56:55.238+0000] {logging_mixin.py:188} INFO - 090106 (22000): 01b8b334-0004-386a-0002-5953000393de: Cannot perform CREATE TABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
[2024-11-29T17:56:55.239+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-29T17:56:55.240+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/energy_usage_prediction.py", line 112, in predict
    cur.execute(create_forecast_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 090106 (22000): 01b8b334-0004-386a-0002-5953000393de: Cannot perform CREATE TABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
[2024-11-29T17:56:55.261+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Electricity_predict, task_id=predict, run_id=manual__2024-11-29T17:56:26.610134+00:00, execution_date=20241129T175626, start_date=20241129T175633, end_date=20241129T175655
[2024-11-29T17:56:55.285+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 269 for task predict (090106 (22000): 01b8b334-0004-386a-0002-5953000393de: Cannot perform CREATE TABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.; 10414)
[2024-11-29T17:56:55.326+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-29T17:56:55.353+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T17:56:55.359+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
