[2024-11-29T05:33:12.290+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-29T05:33:12.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Electricity_predict.predict manual__2024-11-29T05:33:06.670958+00:00 [queued]>
[2024-11-29T05:33:12.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Electricity_predict.predict manual__2024-11-29T05:33:06.670958+00:00 [queued]>
[2024-11-29T05:33:12.379+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-29T05:33:12.400+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): predict> on 2024-11-29 05:33:06.670958+00:00
[2024-11-29T05:33:12.422+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Electricity_predict', 'predict', 'manual__2024-11-29T05:33:06.670958+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/energy_usage_prediction.py', '--cfg-path', '/tmp/tmpb1m_srvl']
[2024-11-29T05:33:12.425+0000] {standard_task_runner.py:91} INFO - Job 262: Subtask predict
[2024-11-29T05:33:12.426+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7961) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T05:33:12.427+0000] {standard_task_runner.py:63} INFO - Started process 7969 to run task
[2024-11-29T05:33:12.499+0000] {task_command.py:426} INFO - Running <TaskInstance: Electricity_predict.predict manual__2024-11-29T05:33:06.670958+00:00 [running]> on host fd43cd87157f
[2024-11-29T05:33:12.621+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Electricity_predict' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T05:33:06.670958+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-29T05:33:06.670958+00:00'
[2024-11-29T05:33:12.622+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-29T05:33:12.817+0000] {logging_mixin.py:188} INFO - 001003 (42000): 01b8b04d-0004-3865-0002-59530002f9ae: SQL compilation error:
syntax error line 3 at position 9 unexpected 'dev'.
syntax error line 3 at position 12 unexpected '.'.
[2024-11-29T05:33:12.818+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-29T05:33:12.818+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/energy_usage_prediction.py", line 101, in predict
    cur.execute(make_prediction_sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01b8b04d-0004-3865-0002-59530002f9ae: SQL compilation error:
syntax error line 3 at position 9 unexpected 'dev'.
syntax error line 3 at position 12 unexpected '.'.
[2024-11-29T05:33:12.832+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Electricity_predict, task_id=predict, run_id=manual__2024-11-29T05:33:06.670958+00:00, execution_date=20241129T053306, start_date=20241129T053312, end_date=20241129T053312
[2024-11-29T05:33:12.850+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 262 for task predict (001003 (42000): 01b8b04d-0004-3865-0002-59530002f9ae: SQL compilation error:
syntax error line 3 at position 9 unexpected 'dev'.
syntax error line 3 at position 12 unexpected '.'.; 7969)
[2024-11-29T05:33:12.885+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-29T05:33:12.903+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T05:33:12.907+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
