[2024-11-29T05:04:13.527+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-29T05:04:13.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Electricity_predict.train manual__2024-11-29T05:04:06.485512+00:00 [queued]>
[2024-11-29T05:04:13.588+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Electricity_predict.train manual__2024-11-29T05:04:06.485512+00:00 [queued]>
[2024-11-29T05:04:13.589+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-29T05:04:13.604+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): train> on 2024-11-29 05:04:06.485512+00:00
[2024-11-29T05:04:13.643+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6187) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T05:04:13.641+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Electricity_predict', 'train', 'manual__2024-11-29T05:04:06.485512+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/energy_usage_prediction.py', '--cfg-path', '/tmp/tmpl9pk7wmh']
[2024-11-29T05:04:13.645+0000] {standard_task_runner.py:63} INFO - Started process 6190 to run task
[2024-11-29T05:04:13.645+0000] {standard_task_runner.py:91} INFO - Job 258: Subtask train
[2024-11-29T05:04:13.703+0000] {task_command.py:426} INFO - Running <TaskInstance: Electricity_predict.train manual__2024-11-29T05:04:06.485512+00:00 [running]> on host fd43cd87157f
[2024-11-29T05:04:13.794+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Electricity_predict' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T05:04:06.485512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-29T05:04:06.485512+00:00'
[2024-11-29T05:04:13.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-29T05:04:14.227+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-29T05:04:14.227+0000] {energy_usage_prediction.py:48} INFO - View created
[2024-11-29T05:04:15.771+0000] {logging_mixin.py:188} INFO - 000904 (42000): 01b8b030-0004-3987-0002-5953000384f6: Uncaught exception of type 'STATEMENT_ERROR' on line 0 at position -1 : SQL compilation error: error line 1 at position 82
invalid identifier 'DEV.ANALYTICS.ELECTRIC_TABLE_V1'
[2024-11-29T05:04:15.772+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-29T05:04:15.773+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/energy_usage_prediction.py", line 49, in train
    cur.execute(create_model_sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01b8b030-0004-3987-0002-5953000384f6: Uncaught exception of type 'STATEMENT_ERROR' on line 0 at position -1 : SQL compilation error: error line 1 at position 82
invalid identifier 'DEV.ANALYTICS.ELECTRIC_TABLE_V1'
[2024-11-29T05:04:15.831+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Electricity_predict, task_id=train, run_id=manual__2024-11-29T05:04:06.485512+00:00, execution_date=20241129T050406, start_date=20241129T050413, end_date=20241129T050415
[2024-11-29T05:04:15.871+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 258 for task train (000904 (42000): 01b8b030-0004-3987-0002-5953000384f6: Uncaught exception of type 'STATEMENT_ERROR' on line 0 at position -1 : SQL compilation error: error line 1 at position 82
invalid identifier 'DEV.ANALYTICS.ELECTRIC_TABLE_V1'; 6190)
[2024-11-29T05:04:15.909+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-29T05:04:15.932+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
