[2024-11-12T03:45:55.511+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T03:45:55.572+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-12T03:45:33.628335+00:00 [queued]>
[2024-11-12T03:45:55.585+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-12T03:45:33.628335+00:00 [queued]>
[2024-11-12T03:45:55.586+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T03:45:55.611+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-12 03:45:33.628335+00:00
[2024-11-12T03:45:55.624+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-11-12T03:45:33.628335+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp16mamj49']
[2024-11-12T03:45:55.627+0000] {standard_task_runner.py:91} INFO - Job 151: Subtask dbt_test
[2024-11-12T03:45:55.635+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2708) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T03:45:55.636+0000] {standard_task_runner.py:63} INFO - Started process 2709 to run task
[2024-11-12T03:45:55.703+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-12T03:45:33.628335+00:00 [running]> on host e9e87141c083
[2024-11-12T03:45:55.924+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T03:45:33.628335+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T03:45:33.628335+00:00'
[2024-11-12T03:45:55.925+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T03:45:55.944+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T03:45:55.948+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T03:45:55.961+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T03:45:58.798+0000] {subprocess.py:93} INFO - [0m03:45:58  Running with dbt=1.8.7
[2024-11-12T03:46:00.269+0000] {subprocess.py:93} INFO - [0m03:46:00  Registered adapter: snowflake=1.8.4
[2024-11-12T03:46:01.015+0000] {subprocess.py:93} INFO - [0m03:46:01  Found 5 models, 1 snapshot, 2 data tests, 2 sources, 459 macros
[2024-11-12T03:46:01.019+0000] {subprocess.py:93} INFO - [0m03:46:01
[2024-11-12T03:46:02.418+0000] {subprocess.py:93} INFO - [0m03:46:02  Concurrency: 1 threads (target='dev')
[2024-11-12T03:46:02.419+0000] {subprocess.py:93} INFO - [0m03:46:02
[2024-11-12T03:46:02.432+0000] {subprocess.py:93} INFO - [0m03:46:02  1 of 2 START test not_null_stock_indicators_date_symbol ........................ [RUN]
[2024-11-12T03:46:03.177+0000] {subprocess.py:93} INFO - [0m03:46:03  1 of 2 ERROR not_null_stock_indicators_date_symbol ............................. [[31mERROR[0m in 0.74s]
[2024-11-12T03:46:03.181+0000] {subprocess.py:93} INFO - [0m03:46:03  2 of 2 START test unique_stock_indicators_date_symbol .......................... [RUN]
[2024-11-12T03:46:03.846+0000] {subprocess.py:93} INFO - [0m03:46:03  2 of 2 ERROR unique_stock_indicators_date_symbol ............................... [[31mERROR[0m in 0.66s]
[2024-11-12T03:46:03.851+0000] {subprocess.py:93} INFO - [0m03:46:03
[2024-11-12T03:46:03.852+0000] {subprocess.py:93} INFO - [0m03:46:03  Finished running 2 data tests in 0 hours 0 minutes and 2.83 seconds (2.83s).
[2024-11-12T03:46:03.912+0000] {subprocess.py:93} INFO - [0m03:46:03
[2024-11-12T03:46:03.913+0000] {subprocess.py:93} INFO - [0m03:46:03  [31mCompleted with 2 errors and 0 warnings:[0m
[2024-11-12T03:46:03.914+0000] {subprocess.py:93} INFO - [0m03:46:03
[2024-11-12T03:46:03.915+0000] {subprocess.py:93} INFO - [0m03:46:03    Database Error in test not_null_stock_indicators_date_symbol (models/schema.yml)
[2024-11-12T03:46:03.915+0000] {subprocess.py:93} INFO -   001003 (42000): SQL compilation error:
[2024-11-12T03:46:03.915+0000] {subprocess.py:93} INFO -   syntax error line 14 at position 10 unexpected ','.
[2024-11-12T03:46:03.916+0000] {subprocess.py:93} INFO -   syntax error line 14 at position 18 unexpected 'is'.
[2024-11-12T03:46:03.916+0000] {subprocess.py:93} INFO -   compiled code at target/run/lab2/models/schema.yml/not_null_stock_indicators_date_symbol.sql
[2024-11-12T03:46:03.917+0000] {subprocess.py:93} INFO - [0m03:46:03
[2024-11-12T03:46:03.917+0000] {subprocess.py:93} INFO - [0m03:46:03    Database Error in test unique_stock_indicators_date_symbol (models/schema.yml)
[2024-11-12T03:46:03.917+0000] {subprocess.py:93} INFO -   001003 (42000): SQL compilation error:
[2024-11-12T03:46:03.918+0000] {subprocess.py:93} INFO -   syntax error line 15 at position 10 unexpected ','.
[2024-11-12T03:46:03.919+0000] {subprocess.py:93} INFO -   syntax error line 15 at position 18 unexpected 'is'.
[2024-11-12T03:46:03.919+0000] {subprocess.py:93} INFO -   syntax error line 22 at position 4 unexpected ')'.
[2024-11-12T03:46:03.919+0000] {subprocess.py:93} INFO -   compiled code at target/run/lab2/models/schema.yml/unique_stock_indicators_date_symbol.sql
[2024-11-12T03:46:03.920+0000] {subprocess.py:93} INFO - [0m03:46:03
[2024-11-12T03:46:03.920+0000] {subprocess.py:93} INFO - [0m03:46:03  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 TOTAL=2
[2024-11-12T03:46:04.716+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-12T03:46:04.719+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T03:46:04.732+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-12T03:46:04.752+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-11-12T03:45:33.628335+00:00, execution_date=20241112T034533, start_date=20241112T034555, end_date=20241112T034604
[2024-11-12T03:46:04.772+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 151 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 2709)
[2024-11-12T03:46:04.808+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T03:46:04.832+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T03:46:04.838+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
