[2024-11-12T03:20:40.004+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T03:20:40.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T03:20:37.868275+00:00 [queued]>
[2024-11-12T03:20:40.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T03:20:37.868275+00:00 [queued]>
[2024-11-12T03:20:40.171+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T03:20:40.208+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 03:20:37.868275+00:00
[2024-11-12T03:20:40.228+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-12T03:20:37.868275+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpufxinmbv']
[2024-11-12T03:20:40.234+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask dbt_run
[2024-11-12T03:20:40.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1616) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T03:20:40.251+0000] {standard_task_runner.py:63} INFO - Started process 1617 to run task
[2024-11-12T03:20:40.376+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T03:20:37.868275+00:00 [running]> on host e9e87141c083
[2024-11-12T03:20:40.880+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T03:20:37.868275+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T03:20:37.868275+00:00'
[2024-11-12T03:20:40.882+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T03:20:40.927+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T03:20:40.933+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T03:20:40.965+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T03:20:44.090+0000] {subprocess.py:93} INFO - [0m03:20:44  Running with dbt=1.8.7
[2024-11-12T03:20:45.530+0000] {subprocess.py:93} INFO - [0m03:20:45  Registered adapter: snowflake=1.8.4
[2024-11-12T03:20:45.679+0000] {subprocess.py:93} INFO - [0m03:20:45  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-11-12T03:20:47.397+0000] {subprocess.py:93} INFO - [0m03:20:47  Encountered an error:
[2024-11-12T03:20:47.398+0000] {subprocess.py:93} INFO - Compilation Error
[2024-11-12T03:20:47.399+0000] {subprocess.py:93} INFO -   Snapshot 'snapshot.lab2.snapshot_moving_avg' (snapshots/snapshot_moving_avg.sql) depends on a node named 'moving_avg_5d' which was not found
[2024-11-12T03:20:48.220+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T03:20:48.221+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T03:20:48.236+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T03:20:48.242+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-12T03:20:37.868275+00:00, execution_date=20241112T032037, start_date=20241112T032040, end_date=20241112T032048
[2024-11-12T03:20:48.262+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1617)
[2024-11-12T03:20:48.305+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T03:20:48.341+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T03:20:48.351+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
