[2024-11-13T19:01:33.150+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T19:01:33.190+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-13T19:01:31.629290+00:00 [queued]>
[2024-11-13T19:01:33.198+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-13T19:01:31.629290+00:00 [queued]>
[2024-11-13T19:01:33.199+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T19:01:33.213+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-13 19:01:31.629290+00:00
[2024-11-13T19:01:33.222+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-13T19:01:31.629290+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpnzss2s22']
[2024-11-13T19:01:33.224+0000] {standard_task_runner.py:91} INFO - Job 184: Subtask dbt_run
[2024-11-13T19:01:33.225+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1903) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-13T19:01:33.226+0000] {standard_task_runner.py:63} INFO - Started process 1904 to run task
[2024-11-13T19:01:33.269+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-13T19:01:31.629290+00:00 [running]> on host d7a7afbedfaf
[2024-11-13T19:01:33.411+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T19:01:31.629290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T19:01:31.629290+00:00'
[2024-11-13T19:01:33.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T19:01:33.440+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-13T19:01:33.441+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-13T19:01:33.454+0000] {subprocess.py:86} INFO - Output:
[2024-11-13T19:01:35.660+0000] {subprocess.py:93} INFO - [0m19:01:35  Running with dbt=1.8.7
[2024-11-13T19:01:36.815+0000] {subprocess.py:93} INFO - [0m19:01:36  Registered adapter: snowflake=1.8.4
[2024-11-13T19:01:37.532+0000] {subprocess.py:93} INFO - [0m19:01:37  Found 6 models, 1 snapshot, 2 data tests, 2 sources, 459 macros
[2024-11-13T19:01:37.536+0000] {subprocess.py:93} INFO - [0m19:01:37
[2024-11-13T19:01:40.272+0000] {subprocess.py:93} INFO - [0m19:01:40  Concurrency: 1 threads (target='dev')
[2024-11-13T19:01:40.272+0000] {subprocess.py:93} INFO - [0m19:01:40
[2024-11-13T19:01:40.283+0000] {subprocess.py:93} INFO - [0m19:01:40  1 of 5 START sql table model analytics.stock_rsi ............................... [RUN]
[2024-11-13T19:01:41.063+0000] {subprocess.py:93} INFO - [0m19:01:41  1 of 5 ERROR creating sql table model analytics.stock_rsi ...................... [[31mERROR[0m in 0.78s]
[2024-11-13T19:01:41.079+0000] {subprocess.py:93} INFO - [0m19:01:41  2 of 5 START sql table model analytics.daily_price_return ...................... [RUN]
[2024-11-13T19:01:42.770+0000] {subprocess.py:93} INFO - [0m19:01:42  2 of 5 OK created sql table model analytics.daily_price_return ................. [[32mSUCCESS 1[0m in 1.69s]
[2024-11-13T19:01:42.774+0000] {subprocess.py:93} INFO - [0m19:01:42  3 of 5 START sql table model analytics.stock_ma ................................ [RUN]
[2024-11-13T19:01:44.196+0000] {subprocess.py:93} INFO - [0m19:01:44  3 of 5 OK created sql table model analytics.stock_ma ........................... [[32mSUCCESS 1[0m in 1.42s]
[2024-11-13T19:01:44.200+0000] {subprocess.py:93} INFO - [0m19:01:44  4 of 5 START sql table model analytics.stock_trend ............................. [RUN]
[2024-11-13T19:01:45.703+0000] {subprocess.py:93} INFO - [0m19:01:45  4 of 5 OK created sql table model analytics.stock_trend ........................ [[32mSUCCESS 1[0m in 1.50s]
[2024-11-13T19:01:45.707+0000] {subprocess.py:93} INFO - [0m19:01:45  5 of 5 SKIP relation analytics.stock_indicators ................................ [[33mSKIP[0m]
[2024-11-13T19:01:45.711+0000] {subprocess.py:93} INFO - [0m19:01:45
[2024-11-13T19:01:45.712+0000] {subprocess.py:93} INFO - [0m19:01:45  Finished running 5 table models in 0 hours 0 minutes and 8.17 seconds (8.17s).
[2024-11-13T19:01:45.784+0000] {subprocess.py:93} INFO - [0m19:01:45
[2024-11-13T19:01:45.785+0000] {subprocess.py:93} INFO - [0m19:01:45  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-13T19:01:45.786+0000] {subprocess.py:93} INFO - [0m19:01:45
[2024-11-13T19:01:45.787+0000] {subprocess.py:93} INFO - [0m19:01:45    Database Error in model stock_rsi (models/intermediate/stock_rsi.sql)
[2024-11-13T19:01:45.788+0000] {subprocess.py:93} INFO -   002003 (42S02): SQL compilation error:
[2024-11-13T19:01:45.788+0000] {subprocess.py:93} INFO -   Object 'REFSTOCK_TABLE' does not exist or not authorized.
[2024-11-13T19:01:45.788+0000] {subprocess.py:93} INFO -   compiled code at target/run/lab2/models/intermediate/stock_rsi.sql
[2024-11-13T19:01:45.789+0000] {subprocess.py:93} INFO - [0m19:01:45
[2024-11-13T19:01:45.789+0000] {subprocess.py:93} INFO - [0m19:01:45  Done. PASS=3 WARN=0 ERROR=1 SKIP=1 TOTAL=5
[2024-11-13T19:01:46.715+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-13T19:01:46.717+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T19:01:46.727+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-13T19:01:46.733+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-13T19:01:31.629290+00:00, execution_date=20241113T190131, start_date=20241113T190133, end_date=20241113T190146
[2024-11-13T19:01:46.749+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 184 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 1904)
[2024-11-13T19:01:46.777+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-13T19:01:46.800+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T19:01:46.806+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
