[2024-11-12T06:31:53.060+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T06:31:53.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T06:31:09.388270+00:00 [queued]>
[2024-11-12T06:31:53.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T06:31:09.388270+00:00 [queued]>
[2024-11-12T06:31:53.106+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T06:31:53.121+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-12 06:31:09.388270+00:00
[2024-11-12T06:31:53.131+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_snapshot', 'manual__2024-11-12T06:31:09.388270+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpwbyqjpea']
[2024-11-12T06:31:53.133+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask dbt_snapshot
[2024-11-12T06:31:53.135+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5545) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T06:31:53.135+0000] {standard_task_runner.py:63} INFO - Started process 5546 to run task
[2024-11-12T06:31:53.179+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_snapshot manual__2024-11-12T06:31:09.388270+00:00 [running]> on host e9e87141c083
[2024-11-12T06:31:53.346+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T06:31:09.388270+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T06:31:09.388270+00:00'
[2024-11-12T06:31:53.347+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T06:31:53.361+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T06:31:53.364+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T06:31:53.376+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T06:31:55.626+0000] {subprocess.py:93} INFO - [0m06:31:55  Running with dbt=1.8.7
[2024-11-12T06:31:56.698+0000] {subprocess.py:93} INFO - [0m06:31:56  Registered adapter: snowflake=1.8.4
[2024-11-12T06:31:57.338+0000] {subprocess.py:93} INFO - [0m06:31:57  Found 5 models, 1 snapshot, 2 data tests, 2 sources, 459 macros
[2024-11-12T06:31:57.341+0000] {subprocess.py:93} INFO - [0m06:31:57
[2024-11-12T06:31:59.254+0000] {subprocess.py:93} INFO - [0m06:31:59  Concurrency: 1 threads (target='dev')
[2024-11-12T06:31:59.255+0000] {subprocess.py:93} INFO - [0m06:31:59
[2024-11-12T06:31:59.268+0000] {subprocess.py:93} INFO - [0m06:31:59  1 of 1 START snapshot snapshot.snapshot_stock_indicators ....................... [RUN]
[2024-11-12T06:32:00.109+0000] {subprocess.py:93} INFO - [0m06:32:00  1 of 1 ERROR snapshotting snapshot.snapshot_stock_indicators ................... [[31mERROR[0m in 0.84s]
[2024-11-12T06:32:00.118+0000] {subprocess.py:93} INFO - [0m06:32:00
[2024-11-12T06:32:00.119+0000] {subprocess.py:93} INFO - [0m06:32:00  Finished running 1 snapshot in 0 hours 0 minutes and 2.78 seconds (2.78s).
[2024-11-12T06:32:00.183+0000] {subprocess.py:93} INFO - [0m06:32:00
[2024-11-12T06:32:00.184+0000] {subprocess.py:93} INFO - [0m06:32:00  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-12T06:32:00.185+0000] {subprocess.py:93} INFO - [0m06:32:00
[2024-11-12T06:32:00.187+0000] {subprocess.py:93} INFO - [0m06:32:00    Database Error in snapshot snapshot_stock_indicators (snapshots/snapshot_stock_indicators.sql)
[2024-11-12T06:32:00.187+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 20 at position 8
[2024-11-12T06:32:00.187+0000] {subprocess.py:93} INFO -   invalid identifier 'SYMBOL_DATE_ID'
[2024-11-12T06:32:00.188+0000] {subprocess.py:93} INFO - [0m06:32:00
[2024-11-12T06:32:00.188+0000] {subprocess.py:93} INFO - [0m06:32:00  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-11-12T06:32:00.991+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-12T06:32:00.993+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T06:32:01.005+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-12T06:32:01.016+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_snapshot, run_id=manual__2024-11-12T06:31:09.388270+00:00, execution_date=20241112T063109, start_date=20241112T063153, end_date=20241112T063201
[2024-11-12T06:32:01.035+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 158 for task dbt_snapshot (Bash command failed. The command returned a non-zero exit code 1.; 5546)
[2024-11-12T06:32:01.057+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T06:32:01.075+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T06:32:01.079+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
