[2024-11-13T18:35:00.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T18:35:01.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-13T18:35:00.232920+00:00 [queued]>
[2024-11-13T18:35:01.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-13T18:35:00.232920+00:00 [queued]>
[2024-11-13T18:35:01.032+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T18:35:01.056+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-13 18:35:00.232920+00:00
[2024-11-13T18:35:01.070+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-13T18:35:00.232920+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpl0gqaqgw']
[2024-11-13T18:35:01.074+0000] {standard_task_runner.py:91} INFO - Job 175: Subtask dbt_run
[2024-11-13T18:35:01.076+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=759) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-13T18:35:01.078+0000] {standard_task_runner.py:63} INFO - Started process 760 to run task
[2024-11-13T18:35:01.174+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-13T18:35:00.232920+00:00 [running]> on host d7a7afbedfaf
[2024-11-13T18:35:01.536+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T18:35:00.232920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T18:35:00.232920+00:00'
[2024-11-13T18:35:01.538+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T18:35:01.577+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-13T18:35:01.581+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-13T18:35:01.600+0000] {subprocess.py:86} INFO - Output:
[2024-11-13T18:35:05.493+0000] {subprocess.py:93} INFO - [0m18:35:05  Running with dbt=1.8.7
[2024-11-13T18:35:08.415+0000] {subprocess.py:93} INFO - [0m18:35:08  Registered adapter: snowflake=1.8.4
[2024-11-13T18:35:09.573+0000] {subprocess.py:93} INFO - [0m18:35:09  Encountered an error:
[2024-11-13T18:35:09.573+0000] {subprocess.py:93} INFO - Compilation Error
[2024-11-13T18:35:09.574+0000] {subprocess.py:93} INFO -   Model 'model.lab2.stock_trend' (models/intermediate/stock_trend.sql) depends on a node named 'stock_summary' which was not found
[2024-11-13T18:35:10.485+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-13T18:35:10.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T18:35:10.499+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-13T18:35:10.507+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-13T18:35:00.232920+00:00, execution_date=20241113T183500, start_date=20241113T183501, end_date=20241113T183510
[2024-11-13T18:35:10.525+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 175 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 760)
[2024-11-13T18:35:10.554+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-13T18:35:10.580+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T18:35:10.588+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
