[2024-11-30T06:32:31.017+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T06:32:31.047+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: complete-dag.dbt_run manual__2024-11-30T06:32:15.946815+00:00 [queued]>
[2024-11-30T06:32:31.056+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: complete-dag.dbt_run manual__2024-11-30T06:32:15.946815+00:00 [queued]>
[2024-11-30T06:32:31.057+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-30T06:32:31.071+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-30 06:32:15.946815+00:00
[2024-11-30T06:32:31.082+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9968) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T06:32:31.082+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'complete-dag', 'dbt_run', 'manual__2024-11-30T06:32:15.946815+00:00', '--job-id', '366', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpun9y_e4c']
[2024-11-30T06:32:31.083+0000] {standard_task_runner.py:63} INFO - Started process 9976 to run task
[2024-11-30T06:32:31.084+0000] {standard_task_runner.py:91} INFO - Job 366: Subtask dbt_run
[2024-11-30T06:32:31.142+0000] {task_command.py:426} INFO - Running <TaskInstance: complete-dag.dbt_run manual__2024-11-30T06:32:15.946815+00:00 [running]> on host b09a94790db6
[2024-11-30T06:32:31.280+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='complete-dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T06:32:15.946815+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T06:32:15.946815+00:00'
[2024-11-30T06:32:31.281+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T06:32:31.283+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-30T06:32:31.284+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-30T06:32:31.298+0000] {subprocess.py:86} INFO - Output:
[2024-11-30T06:32:34.553+0000] {subprocess.py:93} INFO - [0m06:32:34  Running with dbt=1.8.7
[2024-11-30T06:32:35.900+0000] {subprocess.py:93} INFO - [0m06:32:35  Registered adapter: snowflake=1.8.4
[2024-11-30T06:32:36.044+0000] {subprocess.py:93} INFO - [0m06:32:36  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-11-30T06:32:37.454+0000] {subprocess.py:93} INFO - [0m06:32:37  [[33mWARNING[0m]: Deprecated functionality
[2024-11-30T06:32:37.454+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-11-30T06:32:37.455+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-11-30T06:32:37.455+0000] {subprocess.py:93} INFO - information.
[2024-11-30T06:32:37.646+0000] {subprocess.py:93} INFO - [0m06:32:37  Encountered an error:
[2024-11-30T06:32:37.647+0000] {subprocess.py:93} INFO - Compilation Error
[2024-11-30T06:32:37.647+0000] {subprocess.py:93} INFO -   Model 'model.project.electricity_weather_og' (models/ignore/electricity_weather_og.sql) depends on a node named 'electricity_data' which was not found
[2024-11-30T06:32:38.344+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-30T06:32:38.346+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T06:32:38.356+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-30T06:32:38.360+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=complete-dag, task_id=dbt_run, run_id=manual__2024-11-30T06:32:15.946815+00:00, execution_date=20241130T063215, start_date=20241130T063231, end_date=20241130T063238
[2024-11-30T06:32:38.374+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 366 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 9976)
[2024-11-30T06:32:38.416+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-30T06:32:38.425+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
